### ISSUE TITLE
Globus Folder Creation Triggered From Deposit Form

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/RDOS_Publishing#27]
## Description

Our Globus contact mentioned we could have an automatically created subfolder for the depositor to submit their data. Currently, we manually create a folder in the workstation endpoint using their name. However, in pre-curation and post-curation the folder is labelled with the DOI. The Globus contact suggested the folder could be created automatically for a bucket using the DOI. Having an auto-generated folder will save the curator time and effort which can be better focused on more important aspects of curation. This also allows larger submissions to be deposited at the convenience of the researcher.

## To-dos to make the ticket actionable
- [ ] Confirm the specific endpoint that is triggered by the form (workstation?)
- [ ] Confirm the folder can move between endpoints, which means it needs to have the DOI suffix for the name
- [ ] Work with Sarah and others in PRDS to define the steps in this process
- [ ] Contact Sarah for more information regarding this ticket
